In [77]:
! pip install --upgrade pip
!pip install tensorflow
! pip install scikit-learn
! pip install streamlit
!pip install librosa
! pip install numpy
! pip install pandas
! pip install matplotlib

In [78]:
import tensorflow as tf
print(tf.__version__)
print(tf.config.list_physical_devices('GPU'))

2.18.0
[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]


### Importing Libraries

In [79]:
import tensorflow as tf
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

## Data Preprocessing

#### Training Image Preprocessing

In [80]:
# import kagglehub
# import os

# # Define the target folder
# target_folder = "/content/Plant_disease_detection"

# # Ensure the folder exists
# os.makedirs(target_folder, exist_ok=True)

# # Download and extract dataset into the specified folder
# path = kagglehub.dataset_download("vipoooool/new-plant-diseases-dataset")

# print("Path to dataset files:", path)


In [81]:
# import shutil

# # Source and destination paths
# source_path = "/root/.cache/kagglehub/datasets/vipoooool/new-plant-diseases-dataset/versions/2"
# destination_path = "/content/Plant_disease_detection"

# # Copy everything from source to destination
# shutil.copytree(source_path, destination_path, dirs_exist_ok=True)

# print(f"Dataset moved to: {destination_path}")


In [82]:
training_set = tf.keras.utils.image_dataset_from_directory(
    '/content/Plant_disease_detection/New Plant Diseases Dataset(Augmented)/New Plant Diseases Dataset(Augmented)/train',
    labels="inferred", # go inside the train folder and whatever is the name of the directory select it
    label_mode="categorical", # because it's a multiclass problem
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128, 128),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,
)

Found 70295 files belonging to 38 classes.


#### Validation Image PreProcessing

In [83]:
validation_set = tf.keras.utils.image_dataset_from_directory(
    '/content/Plant_disease_detection/New Plant Diseases Dataset(Augmented)/New Plant Diseases Dataset(Augmented)/valid',
    labels="inferred", # go inside the train folder and whatever is the name of the directory select it
    label_mode="categorical", # because it's a multiclass problem
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128, 128),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,

)

Found 17572 files belonging to 38 classes.


In [84]:
training_set

<_PrefetchDataset element_spec=(TensorSpec(shape=(None, 128, 128, 3), dtype=tf.float32, name=None), TensorSpec(shape=(None, 38), dtype=tf.float32, name=None))>

In [85]:
for x, y in training_set:
  print(x,x.shape)
  print(y,y.shape)
  break

tf.Tensor(
[[[[164.25 155.25 158.25]
   [170.25 161.25 164.25]
   [173.   164.   167.  ]
   ...
   [171.75 165.75 167.75]
   [175.   169.   171.  ]
   [175.25 169.25 171.25]]

  [[179.   170.   173.  ]
   [171.75 162.75 165.75]
   [168.75 159.75 162.75]
   ...
   [173.5  167.5  169.5 ]
   [171.75 165.75 167.75]
   [168.5  162.5  164.5 ]]

  [[166.5  157.5  160.5 ]
   [168.75 159.75 162.75]
   [178.5  169.5  172.5 ]
   ...
   [173.5  167.5  169.5 ]
   [172.75 166.75 168.75]
   [175.75 169.75 171.75]]

  ...

  [[140.   131.   136.  ]
   [142.75 133.75 138.75]
   [151.   142.   147.  ]
   ...
   [149.25 143.25 147.25]
   [160.   154.   158.  ]
   [159.75 153.75 157.75]]

  [[144.5  135.5  140.5 ]
   [137.5  128.5  133.5 ]
   [145.5  136.5  141.5 ]
   ...
   [149.75 143.75 147.75]
   [141.25 135.25 139.25]
   [151.   145.   149.  ]]

  [[139.   130.   135.  ]
   [146.75 137.75 142.75]
   [145.   136.   141.  ]
   ...
   [154.   148.   152.  ]
   [155.25 149.25 153.25]
   [143.5  137.5  14

## Building Model

In [86]:
from tensorflow.keras.layers import Dense,Conv2D,MaxPool2D,Flatten
from tensorflow.keras.models import Sequential

In [87]:
model = Sequential()

In [88]:
# Building Convolution layer

In [89]:
# 1st layer
model.add(Conv2D(filters=32,kernel_size=3, padding = 'same', activation='relu', input_shape=[128,128,3])) # basically image box
model.add(Conv2D(filters=32,kernel_size=3, padding = 'same', activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2))

/usr/local/lib/python3.11/dist-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [90]:
# 2nd Layer
model.add(Conv2D(filters=64,kernel_size=3, padding = 'same', activation='relu', input_shape=[128,128,3])) # basically image box
model.add(Conv2D(filters=64,kernel_size=3, padding = 'same', activation='relu'))#2nd layer
model.add(MaxPool2D(pool_size=2,strides=2))

In [91]:
# 3rd Layer
model.add(Conv2D(filters=128,kernel_size=3, padding = 'same', activation='relu', input_shape=[128,128,3])) # basically image box
model.add(Conv2D(filters=128,kernel_size=3, padding = 'same', activation='relu'))#2nd layer
model.add(MaxPool2D(pool_size=2,strides=2))

In [92]:
# 4th layer
model.add(Conv2D(filters=256,kernel_size=3, padding = 'same', activation='relu', input_shape=[128,128,3])) # basically image box
model.add(Conv2D(filters=256,kernel_size=3, padding = 'same', activation='relu'))#2nd layer
model.add(MaxPool2D(pool_size=2,strides=2))

In [93]:
# Flattening
model.add(Flatten())

In [94]:
# Dense layer
model.add(Dense(units=1024, activation='relu')) # units = neuron

In [95]:
# output :- prediction by each class
model.add(Dense(units=38, activation='softmax')) # softmax cause output by each class
                                                 # so select that class which is having maximum probability

### Compiling the model

In [96]:
model.compile(optimizer = 'adam', loss = 'categorical_crossentropy',metrics=['accuracy']) # categorical_crossentropy for multiclasses

In [97]:
model.summary()

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ conv2d_40 (Conv2D)                   │ (None, 128, 128, 32)        │             896 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_41 (Conv2D)                   │ (None, 128, 128, 32)        │           9,248 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_16 (MaxPooling2D)      │ (None, 64, 64, 32)          │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_42 (Conv2D)                   │ (None, 64, 64, 64)          │          18,496 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_43 (Conv2D)                   │ (None, 64, 64, 64)          │          36,928 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_17 (MaxPooling2D)      │ (None, 32, 32, 64)          │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_44 (Conv2D)                   │ (None, 32, 32, 128)         │          73,856 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_45 (Conv2D)                   │ (None, 32, 32, 128)         │         147,584 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_18 (MaxPooling2D)      │ (None, 16, 16, 128)         │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_46 (Conv2D)                   │ (None, 16, 16, 256)         │         295,168 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_47 (Conv2D)                   │ (None, 16, 16, 256)         │         590,080 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_19 (MaxPooling2D)      │ (None, 8, 8, 256)           │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ flatten_4 (Flatten)                  │ (None, 16384)               │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_7 (Dense)                      │ (None, 1024)                │      16,778,240 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_8 (Dense)                      │ (None, 38)                  │          38,950 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 17,989,446 (68.62 MB)

 Trainable params: 17,989,446 (68.62 MB)

 Non-trainable params: 0 (0.00 B)